title: Innovatory MindWorkshop
description: Sandbox badawczy — rezonanse, koherencja, rytmy. IRS.
theme: just-the-docs
color_scheme: dark

url: https://auraliuscore-proto.github.io
baseurl: /Innovatory_MindWorkshop

logo: {{ site.baseurl }}/assets/innowatorium-banner.svg

aux_links:
  GitHub Repo: https://github.com/auraliuscore-proto/Innovatory_MindWorkshop
  Raporty IRS: https://github.com/auraliuscore-proto/Innovatory_MindWorkshop/tree/main/Public/reports

search_enabled: true
search.button: true
footer_content: "© Innovatory MindWorkshop • Docs: CC BY-SA 4.0 • Code: GPL v3"

plugins:
  - jekyll-seo-tag
just_the_docs:
  favicon_ico: /assets/innowatorium-banner.svg
  css:
    - /assets/custom.css
